apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-lazy-bound
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  fstype: ext4
  replication-type: regional-pd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true