apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: nonprod-cluster
spec:
  image: couchbase/server:7.1.1
  paused: false
  antiAffinity: false
  platform: gce
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    fsGroup: 1000
  security:
    adminSecret: cb-auth
  buckets:
    managed: false
  cluster:
    clusterName: nonprod-cluster
    dataServiceMemoryQuota: 4096Mi
    indexServiceMemoryQuota: 2048Mi
    queryServiceMemoryQuota: 256Mi
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 120s
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120s
    autoFailoverServerGroup: false
    autoCompaction:
      databaseFragmentationThreshold:
        percent: 30
        size: 1Gi
      viewFragmentationThreshold:
        percent: 30
        size: 1Gi
      parallelCompaction: false
      timeWindow:
        start: 02:00
        end: 06:00
        abortCompactionOutsideWindow: true
      tombstonePurgeInterval: 72h
  enableOnlineVolumeExpansion: true 
  volumeClaimTemplates: 
  - metadata:
      name: default
    spec:
      storageClassName: standard-lazy-bound 
      resources: 
        requests:
          storage: 5Gi
  - metadata:
      name: data
    spec:
      storageClassName: standard-lazy-bound 
      resources: 
        requests:
          storage: 10Gi
  - metadata:
      name: cindex
    spec:
      storageClassName: standard-lazy-bound 
      resources: 
        requests:
          storage: 5Gi
  servers:
  - name: all_services
    size: 2
    services:
    - data
    - index
    - query
    volumeMounts:
      default: default
      data: data
      index: cindex